version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

defaults: &defaults
  docker:
    - image: cimg/node:24.16

jobs:
  security-scans:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - prodsec/security_scans:
          mode: auto
          open-source-additional-arguments: --exclude=test,scripts
          iac-scan: disabled
          release-branch: master

  tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run linting tasks
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test

  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install & Build
          command: npm install
      - run:
          name: Release
          command: |
            export NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            npx semantic-release@25.0.3

workflows:
  version: 2
  test_and_release:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-vuln-alerts-sca
          filters:
            branches:
              ignore:
                - master

      - security-scans:
          name: Security Scans
          context:
            - open_source-managed

      - tests:
          name: Tests

      - release:
          name: Release
          context:
            - github-release
            - nodejs-install
          requires:
            - Tests
          filters:
            branches:
              only:
                - master
